[package]
name = "optimistic-mutation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.clippy]
enum_glob_use = "deny"
pedantic = "warn"
nursery = "warn"

[dependencies]
sugaru = { path = "../sugaru" }
